apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: app
spec:
  hosts:
  - "*"
  gateways:
  - app-gateway
  http:
  - match:
    - headers:
        cookie:
          regex: "^(.*?;)?(version=test)(;.*)?$"
    route:
    - destination:
        host: app.app.svc.cluster.local
        subset: v2-0
        port:
          number: 5000
  - route:
    - destination:
        host: app.app.svc.cluster.local
        subset: v1-0
        port:
          number: 5000

